/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GestionRouteImport } from './routes/gestion'
import { Route as CotizadorRouteImport } from './routes/cotizador'
import { Route as IndexRouteImport } from './routes/index'

const GestionRoute = GestionRouteImport.update({
  id: '/gestion',
  path: '/gestion',
  getParentRoute: () => rootRouteImport,
} as any)
const CotizadorRoute = CotizadorRouteImport.update({
  id: '/cotizador',
  path: '/cotizador',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cotizador': typeof CotizadorRoute
  '/gestion': typeof GestionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cotizador': typeof CotizadorRoute
  '/gestion': typeof GestionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cotizador': typeof CotizadorRoute
  '/gestion': typeof GestionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cotizador' | '/gestion'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cotizador' | '/gestion'
  id: '__root__' | '/' | '/cotizador' | '/gestion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CotizadorRoute: typeof CotizadorRoute
  GestionRoute: typeof GestionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gestion': {
      id: '/gestion'
      path: '/gestion'
      fullPath: '/gestion'
      preLoaderRoute: typeof GestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizador': {
      id: '/cotizador'
      path: '/cotizador'
      fullPath: '/cotizador'
      preLoaderRoute: typeof CotizadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CotizadorRoute: CotizadorRoute,
  GestionRoute: GestionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
